frontend.enableClientVersionCheck:
  - value: true
    constraints: {}
system.minRetentionDays:
  - value: 0
    constraints: {}
history.EnableConsistentQueryByDomain:
  - value: true
    constraints: {}
#matching.numTasklistReadPartitions:
#  - value: 15
#    constraints: {}
#matching.numTasklistWritePartitions:
#  - value: 15
#    constraints: {}